pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Static Code Analysis') {
            steps {
                bat 'matlab -batch "checkcode(''src'')"'
            }
        }

        stage('Run MATLAB Tests') {
            steps {
                bat 'matlab -batch "runTests"'
            }
        }

        stage('Generate Coverage Report') {
            steps {
                echo 'Coverage report generated by MATLAB'
            }
        }

        stage('Build Artifact') {
            steps {
                bat 'matlab -batch "disp(''Building MATLAB artifact...'')"'
            }
        }

        stage('Publish Test Results') {
            steps {
                junit 'results.xml'
            }
        }

    }

    post {

        success {
            echo 'Pipeline completed successfully!'
        }

        failure {
            echo 'Pipeline failed!'
        }

    }

}